"""
design_holder_for_shim_field_mapping.py

Design a fabrication fixture for independently mapping the magnetic field
generated by a loaded two-plane passive-shim assembly.

Only THREE shim-tray geometry parameters define the fixture:

    1. tray_diameter_mm
    2. tray_thickness_mm
    3. tray_center_separation_mm

All holder, cradle, registration, and center-pointer dimensions are derived
from those three values.

Mechanical concept
------------------
BOTTOM TRAY
    The bottom shim tray drops onto a completely unobstructed flat lower seat.
    Two registration posts sit OUTSIDE the tray footprint in the automatically
    sized annular margin.

TOP TRAY
    The top shim tray is inserted from below and lifted into a three-point
    gravity-supported cradle. Three L-shaped brackets sit outside the tray
    circumference and provide small shelves underneath the tray edge. No
    adhesive or underside attachment is required.

CENTER FINDER
    A removable "goalpost" fixture slips over the two external registration
    posts. Its feet rest on the same lower reference surface as the shim tray.
    A crossbar is automatically raised above the loaded bottom tray, and a
    vertical pointer is exactly centered at x=0, y=0. The pointer tip lands at
    global z=0.

Recommended workflow
--------------------
1. Place the bottom loaded shim tray flat on the lower seat.
2. Lift the top loaded shim tray from below into the upper three-point cradle.
3. Drop the removable center finder over the two external posts.
4. Move the mapping robot probe to the pointer tip.
5. Remove the center finder.
6. Map the shim-only field.

Coordinate convention
---------------------
``separation`` is the CENTER-TO-CENTER separation of the two shim trays.

For separation S and tray thickness T:

    bottom tray center      = -S/2
    top tray center         = +S/2

    bottom tray lower face  = -S/2 - T/2
    bottom tray upper face  = -S/2 + T/2

    top tray lower face     = +S/2 - T/2
    top tray upper face     = +S/2 + T/2

    mapping center          = 0

For S=97 mm and T=6 mm:

    bottom tray center      = -48.5 mm
    top tray center         = +48.5 mm
    center-to-center        = 97.0 mm

Units
-----
Geometry is generated directly in millimeters because STL is unitless and
most slicers interpret STL coordinates as millimeters.

Dependencies
------------
pip install numpy trimesh manifold3d

Examples
--------
python design_holder_for_shim_field_mapping.py

python design_holder_for_shim_field_mapping.py \
    --tray-diameter 180 \
    --tray-thickness 6 \
    --separation 97

python design_holder_for_shim_field_mapping.py \
    --tray-diameter 180 \
    --tray-thickness 6 \
    --separation 97 \
    --output-dir ./data/shim_mapping_fixture
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import trimesh


BOOLEAN_ENGINE = "manifold"
BOOLEAN_OVERLAP_MM = 0.25


# ============================================================================
# DEFAULT SHIM-TRAY GEOMETRY
# ============================================================================

DEFAULT_TRAY_DIAMETER_MM = 180.0
DEFAULT_TRAY_THICKNESS_MM = 6.0
DEFAULT_SEPARATION_MM = 97.0


# ============================================================================
# DERIVED DIMENSIONS
# ============================================================================

@dataclass(frozen=True)
class DerivedDimensions:
    """
    All fabrication dimensions derived from tray diameter D and thickness T.
    """

    # Primary tray geometry
    tray_diameter: float
    tray_radius: float
    tray_thickness: float
    separation: float

    # Main support
    radial_margin: float
    holder_diameter: float
    support_disc_thickness: float

    # Side walls
    side_wall_thickness: float
    side_wall_width: float
    side_wall_center_radius: float

    # Top three-point cradle
    cradle_clearance: float
    cradle_shelf_depth: float
    cradle_shelf_width: float
    cradle_shelf_thickness: float
    cradle_hanger_thickness: float
    cradle_hanger_width: float
    cradle_hanger_radius: float

    # Registration posts
    post_diameter: float
    post_radius: float
    post_projection: float
    post_hole_clearance: float

    # Center-finder goalpost
    centerer_foot_width: float
    centerer_foot_depth: float
    centerer_crossbar_thickness: float
    centerer_crossbar_depth: float
    centerer_clearance_above_tray: float
    pointer_rod_diameter: float
    pointer_tip_height: float


def derive_dimensions(
    tray_diameter_mm: float,
    tray_thickness_mm: float,
    separation_mm: float,
) -> DerivedDimensions:
    """
    Derive the full holder geometry from only D, T, and S.

    The proportional rules are intentionally conservative for FDM printing.
    Small lower bounds prevent impractically thin features for small fixtures.
    """

    D = float(tray_diameter_mm)
    T = float(tray_thickness_mm)
    S = float(separation_mm)

    if D <= 0:
        raise ValueError("tray_diameter_mm must be positive.")
    if T <= 0:
        raise ValueError("tray_thickness_mm must be positive.")
    if S <= T:
        raise ValueError(
            "separation_mm must be larger than tray_thickness_mm."
        )

    R = D / 2.0

    # Annular structural margin outside the actual shim tray.
    radial_margin = max(
        2.0 * T,
        0.06 * D,
        8.0,
    )

    holder_diameter = (
        D
        + 2.0 * radial_margin
    )

    support_disc_thickness = max(
        0.67 * T,
        3.0,
    )

    # Main side walls at +/-X.
    side_wall_thickness = max(
        T,
        4.0,
    )

    side_wall_width = max(
        3.0 * T,
        0.08 * D,
        12.0,
    )

    side_wall_center_radius = (
        holder_diameter / 2.0
        - radial_margin * 0.35
    )

    # Upper cradle.
    cradle_clearance = max(
        0.08 * T,
        0.4,
    )

    cradle_shelf_depth = max(
        1.5 * T,
        8.0,
    )

    cradle_shelf_width = max(
        3.0 * T,
        0.09 * D,
        12.0,
    )

    cradle_shelf_thickness = max(
        0.50 * T,
        2.5,
    )

    cradle_hanger_thickness = max(
        0.65 * T,
        3.0,
    )

    cradle_hanger_width = cradle_shelf_width

    # Inner hanger surface lies just outside the tray circumference.
    cradle_hanger_radius = (
        R
        + cradle_clearance
        + cradle_hanger_thickness / 2.0
    )

    # Registration posts live in the annular margin, completely outside tray.
    post_diameter = max(
        0.65 * T,
        3.5,
    )

    post_radius = (
        R
        + 0.55 * radial_margin
    )

    post_projection = max(
        1.25 * T,
        6.0,
    )

    post_hole_clearance = max(
        0.06 * T,
        0.30,
    )

    # Removable center-finder.
    centerer_foot_width = max(
        2.2 * post_diameter,
        1.5 * T,
    )

    centerer_foot_depth = centerer_foot_width

    centerer_crossbar_thickness = max(
        0.55 * T,
        3.0,
    )

    centerer_crossbar_depth = max(
        1.5 * T,
        8.0,
    )

    # Keep crossbar safely above loaded magnets/shim surface.
    centerer_clearance_above_tray = max(
        1.5 * T,
        8.0,
    )

    pointer_rod_diameter = max(
        0.55 * T,
        3.0,
    )

    pointer_tip_height = max(
        0.65 * T,
        3.0,
    )

    return DerivedDimensions(
        tray_diameter=D,
        tray_radius=R,
        tray_thickness=T,
        separation=S,
        radial_margin=radial_margin,
        holder_diameter=holder_diameter,
        support_disc_thickness=support_disc_thickness,
        side_wall_thickness=side_wall_thickness,
        side_wall_width=side_wall_width,
        side_wall_center_radius=side_wall_center_radius,
        cradle_clearance=cradle_clearance,
        cradle_shelf_depth=cradle_shelf_depth,
        cradle_shelf_width=cradle_shelf_width,
        cradle_shelf_thickness=cradle_shelf_thickness,
        cradle_hanger_thickness=cradle_hanger_thickness,
        cradle_hanger_width=cradle_hanger_width,
        cradle_hanger_radius=cradle_hanger_radius,
        post_diameter=post_diameter,
        post_radius=post_radius,
        post_projection=post_projection,
        post_hole_clearance=post_hole_clearance,
        centerer_foot_width=centerer_foot_width,
        centerer_foot_depth=centerer_foot_depth,
        centerer_crossbar_thickness=centerer_crossbar_thickness,
        centerer_crossbar_depth=centerer_crossbar_depth,
        centerer_clearance_above_tray=centerer_clearance_above_tray,
        pointer_rod_diameter=pointer_rod_diameter,
        pointer_tip_height=pointer_tip_height,
    )


# ============================================================================
# REFERENCE PLANES
# ============================================================================

def reference_planes(d: DerivedDimensions) -> dict[str, float]:
    h = d.separation / 2.0
    ht = d.tray_thickness / 2.0

    return {
        "bottom_tray_center_z":
            -h,

        "top_tray_center_z":
            +h,

        "bottom_tray_lower_face_z":
            -h - ht,

        "bottom_tray_upper_face_z":
            -h + ht,

        "top_tray_lower_face_z":
            +h - ht,

        "top_tray_upper_face_z":
            +h + ht,

        "mapping_center_z":
            0.0,
    }


# ============================================================================
# TRIMESH HELPERS
# ============================================================================

def as_mesh(mesh_like):
    if isinstance(mesh_like, trimesh.Trimesh):
        return mesh_like

    if isinstance(mesh_like, trimesh.Scene):
        geometries = list(mesh_like.geometry.values())

        if not geometries:
            raise RuntimeError("Boolean returned an empty Scene.")

        return trimesh.util.concatenate(geometries)

    raise TypeError(
        f"Unexpected mesh type: {type(mesh_like)}"
    )


def clean_mesh(mesh):
    mesh = as_mesh(mesh)

    try:
        mesh.remove_unreferenced_vertices()
    except Exception:
        pass

    try:
        mesh.merge_vertices()
    except Exception:
        pass

    try:
        trimesh.repair.fix_normals(
            mesh,
            multibody=True,
        )
    except Exception:
        pass

    return mesh


def union(meshes, description):
    meshes = [
        clean_mesh(mesh)
        for mesh in meshes
    ]

    bad = [
        index
        for index, mesh in enumerate(meshes)
        if not mesh.is_volume
    ]

    if bad:
        raise RuntimeError(
            f"{description}: invalid input solids {bad}."
        )

    result = trimesh.boolean.union(
        meshes,
        engine=BOOLEAN_ENGINE,
    )

    if result is None:
        raise RuntimeError(
            f"{description}: Boolean union returned None."
        )

    result = clean_mesh(result)

    if not result.is_watertight:
        raise RuntimeError(
            f"{description}: union result is not watertight."
        )

    if not result.is_volume:
        raise RuntimeError(
            f"{description}: union result is not a valid volume."
        )

    return result


def difference(
    base,
    cutters,
    description,
):
    base = clean_mesh(base)

    cutters = [
        clean_mesh(cutter)
        for cutter in cutters
    ]

    if not base.is_volume:
        raise RuntimeError(
            f"{description}: base is not a valid volume."
        )

    bad = [
        index
        for index, cutter in enumerate(cutters)
        if not cutter.is_volume
    ]

    if bad:
        raise RuntimeError(
            f"{description}: invalid cutter volumes {bad}."
        )

    result = trimesh.boolean.difference(
        [
            base,
            *cutters,
        ],
        engine=BOOLEAN_ENGINE,
    )

    if result is None:
        raise RuntimeError(
            f"{description}: Boolean difference returned None."
        )

    result = clean_mesh(result)

    if not result.is_watertight:
        raise RuntimeError(
            f"{description}: result is not watertight."
        )

    if not result.is_volume:
        raise RuntimeError(
            f"{description}: result is not a valid volume."
        )

    return result


def box_at(
    extents,
    center,
):
    mesh = trimesh.creation.box(
        extents=np.asarray(
            extents,
            dtype=float,
        )
    )

    mesh.apply_translation(
        np.asarray(
            center,
            dtype=float,
        )
    )

    return mesh


def cylinder_at(
    diameter,
    height,
    center,
    sections=96,
):
    mesh = trimesh.creation.cylinder(
        radius=float(diameter) / 2.0,
        height=float(height),
        sections=int(sections),
    )

    mesh.apply_translation(
        np.asarray(
            center,
            dtype=float,
        )
    )

    return mesh


def disc(
    diameter,
    thickness,
    center_z,
    sections=256,
):
    return cylinder_at(
        diameter=diameter,
        height=thickness,
        center=[
            0.0,
            0.0,
            center_z,
        ],
        sections=sections,
    )


def rotate_about_z(
    mesh,
    angle_rad,
):
    transform = (
        trimesh.transformations.rotation_matrix(
            float(angle_rad),
            [0.0, 0.0, 1.0],
        )
    )

    mesh.apply_transform(
        transform
    )

    return mesh


# ============================================================================
# MAIN HOLDER
# ============================================================================

def build_holder(
    d: DerivedDimensions,
):
    """
    Build the rigid shim-field mapping holder.

    Bottom tray seat is completely flat and unobstructed.
    Registration posts sit beyond the actual shim-tray radius.
    """

    p = reference_planes(d)

    # ----------------------------------------------------------------------
    # Bottom and top structural discs
    # ----------------------------------------------------------------------

    bottom_support_z = (
        p["bottom_tray_lower_face_z"]
    )

    top_support_z = (
        p["top_tray_upper_face_z"]
    )

    bottom_disc = disc(
        diameter=
            d.holder_diameter,
        thickness=
            d.support_disc_thickness,
        center_z=
            bottom_support_z
            - d.support_disc_thickness / 2.0,
    )

    top_disc = disc(
        diameter=
            d.holder_diameter,
        thickness=
            d.support_disc_thickness,
        center_z=
            top_support_z
            + d.support_disc_thickness / 2.0,
    )

    # ----------------------------------------------------------------------
    # Two vertical walls at +/-X.
    #
    # Front/back remain open for mapping robot access.
    # ----------------------------------------------------------------------

    outer_bottom_z = (
        bottom_support_z
        - d.support_disc_thickness
    )

    outer_top_z = (
        top_support_z
        + d.support_disc_thickness
    )

    wall_height = (
        outer_top_z
        - outer_bottom_z
        + 2.0 * BOOLEAN_OVERLAP_MM
    )

    wall_center_z = (
        outer_bottom_z
        + outer_top_z
    ) / 2.0

    walls = []

    for sign in (
        -1.0,
        +1.0,
    ):

        wall = box_at(
            extents=[
                d.side_wall_thickness,
                d.side_wall_width,
                wall_height,
            ],
            center=[
                sign
                * d.side_wall_center_radius,
                0.0,
                wall_center_z,
            ],
        )

        walls.append(
            wall
        )

    # ----------------------------------------------------------------------
    # Upper gravity cradle.
    #
    # Three L brackets:
    #   vertical hanger is OUTSIDE tray circumference;
    #   horizontal shelf supports tray from underneath.
    #
    # The tray is brought in from below, lifted above the shelves, centered
    # between the three hangers, then lowered onto the shelves.
    # ----------------------------------------------------------------------

    cradle_parts = []

    top_disc_inner_surface_z = (
        top_support_z
    )

    top_tray_lower_face_z = (
        p["top_tray_lower_face_z"]
    )

    hanger_top_z = (
        top_disc_inner_surface_z
        + BOOLEAN_OVERLAP_MM
    )

    hanger_bottom_z = (
        top_tray_lower_face_z
        - d.cradle_shelf_thickness
        - BOOLEAN_OVERLAP_MM
    )

    hanger_height = (
        hanger_top_z
        - hanger_bottom_z
    )

    hanger_center_z = (
        hanger_top_z
        + hanger_bottom_z
    ) / 2.0

    for angle_deg in (
        30.0,
        150.0,
        270.0,
    ):

        angle = np.deg2rad(
            angle_deg
        )

        radial = np.array(
            [
                np.cos(angle),
                np.sin(angle),
            ],
            dtype=float,
        )

        # Vertical outer hanger.
        hanger_xy = (
            radial
            * d.cradle_hanger_radius
        )

        hanger = box_at(
            extents=[
                d.cradle_hanger_thickness,
                d.cradle_hanger_width,
                hanger_height,
            ],
            center=[
                hanger_xy[0],
                hanger_xy[1],
                hanger_center_z,
            ],
        )

        rotate_about_z(
            hanger,
            angle,
        )

        # Shelf extends inward from hanger and supports tray edge.
        shelf_center_radius = (
            d.cradle_hanger_radius
            - d.cradle_hanger_thickness / 2.0
            - d.cradle_shelf_depth / 2.0
            + BOOLEAN_OVERLAP_MM
        )

        shelf_xy = (
            radial
            * shelf_center_radius
        )

        shelf = box_at(
            extents=[
                d.cradle_shelf_depth
                + 2.0 * BOOLEAN_OVERLAP_MM,
                d.cradle_shelf_width,
                d.cradle_shelf_thickness,
            ],
            center=[
                shelf_xy[0],
                shelf_xy[1],
                top_tray_lower_face_z
                - d.cradle_shelf_thickness / 2.0
                + BOOLEAN_OVERLAP_MM,
            ],
        )

        rotate_about_z(
            shelf,
            angle,
        )

        cradle_parts.extend(
            [
                hanger,
                shelf,
            ]
        )

    # ----------------------------------------------------------------------
    # Two registration posts on the annular margin OUTSIDE tray footprint.
    # They do not obstruct placing the bottom tray.
    # ----------------------------------------------------------------------

    post_base_z = (
        bottom_support_z
        - BOOLEAN_OVERLAP_MM
    )

    post_top_z = (
        bottom_support_z
        + d.post_projection
    )

    post_height = (
        post_top_z
        - post_base_z
    )

    post_center_z = (
        post_top_z
        + post_base_z
    ) / 2.0

    posts = []

    for x in (
        -d.post_radius,
        +d.post_radius,
    ):

        post = cylinder_at(
            diameter=
                d.post_diameter,
            height=
                post_height,
            center=[
                x,
                0.0,
                post_center_z,
            ],
        )

        posts.append(
            post
        )

    holder = union(
        [
            bottom_disc,
            top_disc,
            *walls,
            *cradle_parts,
            *posts,
        ],
        "shim-field mapping holder",
    )

    metadata = {
        **p,

        "bottom_support_surface_z":
            bottom_support_z,

        "top_support_surface_z":
            top_support_z,

        "holder_diameter":
            d.holder_diameter,

        "post_radius":
            d.post_radius,

        "post_spacing":
            2.0 * d.post_radius,

        "post_diameter":
            d.post_diameter,
    }

    return (
        holder,
        metadata,
    )


# ============================================================================
# REMOVABLE CENTER FINDER
# ============================================================================

def build_center_finder(
    d: DerivedDimensions,
):
    """
    Build a removable goalpost-style center finder.

    The two feet slip over the external holder posts. The feet rest on the
    lower support plane, OUTSIDE the bottom tray.

    The horizontal crossbar is elevated above the loaded bottom tray.
    A vertical central pointer then rises exactly to z=0.
    """

    p = reference_planes(d)

    # ----------------------------------------------------------------------
    # Vertical reference:
    # local z=0 of center finder rests on bottom holder support surface.
    # ----------------------------------------------------------------------

    base_global_z = (
        p["bottom_tray_lower_face_z"]
    )

    target_tip_local_z = (
        -base_global_z
    )

    # Tray top relative to support seat = tray thickness.
    crossbar_bottom_local_z = (
        d.tray_thickness
        + d.centerer_clearance_above_tray
    )

    crossbar_center_local_z = (
        crossbar_bottom_local_z
        + d.centerer_crossbar_thickness / 2.0
    )

    crossbar_top_local_z = (
        crossbar_bottom_local_z
        + d.centerer_crossbar_thickness
    )

    if crossbar_top_local_z >= target_tip_local_z:
        raise ValueError(
            "Derived center-finder crossbar is too high for this "
            "tray separation. Increase separation or reduce tray thickness."
        )

    # ----------------------------------------------------------------------
    # Goalpost legs
    # ----------------------------------------------------------------------

    leg_height = (
        crossbar_top_local_z
        + BOOLEAN_OVERLAP_MM
    )

    leg_center_z = (
        leg_height / 2.0
    )

    legs = []

    for x in (
        -d.post_radius,
        +d.post_radius,
    ):

        leg = box_at(
            extents=[
                d.centerer_foot_width,
                d.centerer_foot_depth,
                leg_height,
            ],
            center=[
                x,
                0.0,
                leg_center_z,
            ],
        )

        legs.append(
            leg
        )

    # ----------------------------------------------------------------------
    # Horizontal crossbar
    # ----------------------------------------------------------------------

    crossbar_length = (
        2.0 * d.post_radius
        + d.centerer_foot_width
    )

    crossbar = box_at(
        extents=[
            crossbar_length,
            d.centerer_crossbar_depth,
            d.centerer_crossbar_thickness,
        ],
        center=[
            0.0,
            0.0,
            crossbar_center_local_z,
        ],
    )

    body = union(
        [
            *legs,
            crossbar,
        ],
        "center-finder goalpost body",
    )

    # ----------------------------------------------------------------------
    # Registration holes through the lower ends of the two legs.
    # Holes are slightly larger than holder posts.
    # ----------------------------------------------------------------------

    hole_diameter = (
        d.post_diameter
        + 2.0 * d.post_hole_clearance
    )

    hole_height = (
        d.post_projection
        + 1.0
    )

    holes = []

    for x in (
        -d.post_radius,
        +d.post_radius,
    ):

        hole = cylinder_at(
            diameter=
                hole_diameter,
            height=
                hole_height,
            center=[
                x,
                0.0,
                hole_height / 2.0
                - 0.25,
            ],
        )

        holes.append(
            hole
        )

    body = difference(
        body,
        holes,
        "center-finder registration holes",
    )

    # ----------------------------------------------------------------------
    # Central vertical pointer.
    #
    # Cylindrical rod starts at crossbar and ends at base of conical tip.
    # ----------------------------------------------------------------------

    cone_height = (
        d.pointer_tip_height
    )

    cone_base_z = (
        target_tip_local_z
        - cone_height
    )

    rod_bottom_z = (
        crossbar_top_local_z
        - BOOLEAN_OVERLAP_MM
    )

    rod_top_z = (
        cone_base_z
        + BOOLEAN_OVERLAP_MM
    )

    rod_height = (
        rod_top_z
        - rod_bottom_z
    )

    if rod_height <= 0:
        raise ValueError(
            "Derived pointer rod has non-positive height."
        )

    rod = cylinder_at(
        diameter=
            d.pointer_rod_diameter,
        height=
            rod_height,
        center=[
            0.0,
            0.0,
            (
                rod_bottom_z
                + rod_top_z
            ) / 2.0,
        ],
    )

    tip = trimesh.creation.cone(
        radius=
            d.pointer_rod_diameter / 2.0,
        height=
            cone_height,
        sections=96,
    )

    # Position robustly from actual cone bounds.
    tip_bottom = float(
        tip.bounds[
            0,
            2
        ]
    )

    tip.apply_translation(
        [
            0.0,
            0.0,
            cone_base_z
            - tip_bottom,
        ]
    )

    center_finder = union(
        [
            body,
            rod,
            tip,
        ],
        "center finder",
    )

    # Normalize local base to exactly z=0.
    center_finder.apply_translation(
        [
            0.0,
            0.0,
            -float(
                center_finder.bounds[
                    0,
                    2
                ]
            ),
        ]
    )

    actual_tip_height = float(
        center_finder.bounds[
            1,
            2
        ]
    )

    if not np.isclose(
        actual_tip_height,
        target_tip_local_z,
        atol=0.05,
    ):
        raise RuntimeError(
            "Center-finder tip-height verification failed: "
            f"expected {target_tip_local_z:.3f} mm, "
            f"got {actual_tip_height:.3f} mm."
        )

    metadata = {
        **p,

        "fixture_base_global_z_when_installed":
            base_global_z,

        "fixture_tip_height":
            actual_tip_height,

        "fixture_tip_global_z_when_installed":
            base_global_z
            + actual_tip_height,

        "crossbar_bottom_above_support":
            crossbar_bottom_local_z,

        "crossbar_clearance_above_tray":
            d.centerer_clearance_above_tray,

        "registration_hole_diameter":
            hole_diameter,

        "post_spacing":
            2.0 * d.post_radius,
    }

    return (
        center_finder,
        metadata,
    )


# ============================================================================
# VISUALIZATION
# ============================================================================

def show_holder(
    holder,
):
    mesh = holder.copy()
    mesh.visual.face_colors = (
        [180, 180, 205, 255]
    )

    trimesh.Scene(
        {
            "holder":
                mesh,
        }
    ).show()


def show_center_finder(
    center_finder,
):
    mesh = center_finder.copy()
    mesh.visual.face_colors = (
        [230, 175, 90, 255]
    )

    trimesh.Scene(
        {
            "center_finder":
                mesh,
        }
    ).show()


def show_assembled(
    holder,
    center_finder,
    d: DerivedDimensions,
    holder_metadata,
):
    """
    Visualization of actual geometry plus proxy top/bottom shim trays.
    Proxy trays are visualization-only and are NOT exported.
    """

    scene = trimesh.Scene()

    holder_display = holder.copy()
    holder_display.visual.face_colors = (
        [180, 180, 205, 185]
    )

    scene.add_geometry(
        holder_display,
        node_name="holder",
    )

    bottom_tray = disc(
        diameter=
            d.tray_diameter,
        thickness=
            d.tray_thickness,
        center_z=
            holder_metadata[
                "bottom_tray_center_z"
            ],
    )

    top_tray = disc(
        diameter=
            d.tray_diameter,
        thickness=
            d.tray_thickness,
        center_z=
            holder_metadata[
                "top_tray_center_z"
            ],
    )

    bottom_tray.visual.face_colors = (
        [95, 175, 230, 150]
    )

    top_tray.visual.face_colors = (
        [95, 175, 230, 150]
    )

    scene.add_geometry(
        bottom_tray,
        node_name=
            "bottom_shim_tray_proxy",
    )

    scene.add_geometry(
        top_tray,
        node_name=
            "top_shim_tray_proxy",
    )

    finder_display = center_finder.copy()

    finder_display.apply_translation(
        [
            0.0,
            0.0,
            holder_metadata[
                "bottom_support_surface_z"
            ],
        ]
    )

    finder_display.visual.face_colors = (
        [230, 175, 90, 245]
    )

    scene.add_geometry(
        finder_display,
        node_name=
            "center_finder_installed",
    )

    origin = trimesh.creation.icosphere(
        subdivisions=2,
        radius=max(
            0.15 * d.tray_thickness,
            0.8,
        ),
    )

    origin.visual.face_colors = (
        [40, 230, 40, 255]
    )

    scene.add_geometry(
        origin,
        node_name=
            "origin_0_0_0",
    )

    scene.show()


# ============================================================================
# EXPORT / VERIFICATION
# ============================================================================

def export_and_verify(
    mesh,
    path,
    label,
):
    path = Path(
        path
    )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if not mesh.is_watertight:
        raise RuntimeError(
            f"{label} is not watertight; refusing export."
        )

    if not mesh.is_volume:
        raise RuntimeError(
            f"{label} is not a valid volume; refusing export."
        )

    mesh.export(
        path
    )

    reloaded = trimesh.load(
        path,
        force="mesh",
    )

    print(
        f"\n{label}"
    )

    print(
        f"  STL: "
        f"{path}"
    )

    print(
        f"  watertight: "
        f"{reloaded.is_watertight}"
    )

    print(
        f"  volume: "
        f"{reloaded.is_volume}"
    )

    print(
        f"  extents [mm]: "
        f"{np.asarray(reloaded.extents)}"
    )

    if not reloaded.is_watertight:
        raise RuntimeError(
            f"Reloaded {label} STL is not watertight."
        )

    if not reloaded.is_volume:
        raise RuntimeError(
            f"Reloaded {label} STL is not a valid volume."
        )

    return path


# ============================================================================
# REPORTING
# ============================================================================

def print_design_report(
    d: DerivedDimensions,
    holder_metadata,
    center_metadata,
):
    print(
        "\n"
        + "=" * 82
    )

    print(
        "SHIM FIELD-MAPPING HOLDER"
    )

    print(
        "=" * 82
    )

    print(
        "\nINPUT SHIM-TRAY GEOMETRY"
    )

    print(
        f"  tray diameter: "
        f"{d.tray_diameter:.3f} mm"
    )

    print(
        f"  tray thickness: "
        f"{d.tray_thickness:.3f} mm"
    )

    print(
        f"  tray center-to-center separation: "
        f"{d.separation:.3f} mm"
    )

    print(
        "\nREFERENCE PLANES"
    )

    print(
        f"  bottom tray center: "
        f"{holder_metadata['bottom_tray_center_z']:+.3f} mm"
    )

    print(
        f"  top tray center: "
        f"{holder_metadata['top_tray_center_z']:+.3f} mm"
    )

    print(
        f"  bottom tray lower face: "
        f"{holder_metadata['bottom_tray_lower_face_z']:+.3f} mm"
    )

    print(
        f"  bottom tray upper face: "
        f"{holder_metadata['bottom_tray_upper_face_z']:+.3f} mm"
    )

    print(
        f"  top tray lower face: "
        f"{holder_metadata['top_tray_lower_face_z']:+.3f} mm"
    )

    print(
        f"  top tray upper face: "
        f"{holder_metadata['top_tray_upper_face_z']:+.3f} mm"
    )

    print(
        "  mapping center: "
        "(0.000, 0.000, 0.000) mm"
    )

    print(
        "\nAUTOMATICALLY DERIVED HOLDER DIMENSIONS"
    )

    print(
        f"  holder diameter: "
        f"{d.holder_diameter:.3f} mm"
    )

    print(
        f"  radial structural margin: "
        f"{d.radial_margin:.3f} mm"
    )

    print(
        f"  support-disc thickness: "
        f"{d.support_disc_thickness:.3f} mm"
    )

    print(
        f"  side-wall thickness x width: "
        f"{d.side_wall_thickness:.3f} x "
        f"{d.side_wall_width:.3f} mm"
    )

    print(
        f"  upper cradle clearance: "
        f"{d.cradle_clearance:.3f} mm"
    )

    print(
        f"  upper cradle shelf depth: "
        f"{d.cradle_shelf_depth:.3f} mm"
    )

    print(
        f"  registration post diameter: "
        f"{d.post_diameter:.3f} mm"
    )

    print(
        f"  registration post spacing: "
        f"{2.0*d.post_radius:.3f} mm"
    )

    print(
        "\nCENTER FINDER"
    )

    print(
        f"  crossbar clearance above bottom tray: "
        f"{center_metadata['crossbar_clearance_above_tray']:.3f} mm"
    )

    print(
        f"  center-pointer base-to-tip height: "
        f"{center_metadata['fixture_tip_height']:.3f} mm"
    )

    print(
        f"  pointer global tip Z when installed: "
        f"{center_metadata['fixture_tip_global_z_when_installed']:+.6f} mm"
    )

    print(
        "=" * 82
    )


# ============================================================================
# CLI
# ============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Design a passive-shim field-mapping holder from only the shim "
            "tray diameter, tray thickness, and tray center separation."
        )
    )

    parser.add_argument(
        "--tray-diameter",
        type=float,
        default=
            DEFAULT_TRAY_DIAMETER_MM,
        help=(
            "Shim-tray diameter in mm. "
            f"Default: {DEFAULT_TRAY_DIAMETER_MM:g}."
        ),
    )

    parser.add_argument(
        "--tray-thickness",
        type=float,
        default=
            DEFAULT_TRAY_THICKNESS_MM,
        help=(
            "Shim-tray physical thickness in mm. "
            f"Default: {DEFAULT_TRAY_THICKNESS_MM:g}."
        ),
    )

    parser.add_argument(
        "--separation",
        type=float,
        default=
            DEFAULT_SEPARATION_MM,
        help=(
            "CENTER-TO-CENTER separation of the two shim trays in mm. "
            f"Default: {DEFAULT_SEPARATION_MM:g}."
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=
            Path(
                "./shim_field_mapping_holder_output"
            ),
    )

    parser.add_argument(
        "--no-show",
        action=
            "store_true",
        help=(
            "Generate/export without opening Trimesh viewers."
        ),
    )

    return parser.parse_args()


# ============================================================================
# MAIN
# ============================================================================

def main():
    args = parse_args()

    d = derive_dimensions(
        tray_diameter_mm=
            args.tray_diameter,
        tray_thickness_mm=
            args.tray_thickness,
        separation_mm=
            args.separation,
    )

    holder, holder_metadata = build_holder(
        d
    )

    center_finder, center_metadata = (
        build_center_finder(
            d
        )
    )

    print_design_report(
        d,
        holder_metadata,
        center_metadata,
    )

    output_dir = Path(
        args.output_dir
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    holder_path = export_and_verify(
        holder,
        output_dir
        / "shim_field_mapping_holder.stl",
        "Shim field-mapping holder",
    )

    center_path = export_and_verify(
        center_finder,
        output_dir
        / "shim_field_mapping_center_finder.stl",
        "Registered center finder",
    )

    if not args.no_show:
        show_holder(
            holder
        )

        show_center_finder(
            center_finder
        )

        show_assembled(
            holder=
                holder,
            center_finder=
                center_finder,
            d=
                d,
            holder_metadata=
                holder_metadata,
        )

    return {
        "derived_dimensions":
            d,

        "holder":
            holder,

        "center_finder":
            center_finder,

        "holder_metadata":
            holder_metadata,

        "center_metadata":
            center_metadata,

        "holder_stl":
            holder_path,

        "center_finder_stl":
            center_path,
    }


if __name__ == "__main__":
    main()
